### ISSUE TITLE
Install Issues (0.9.1)

### ISSUE THREAD

**Issue by PhilippSPOTTERON** [thobbsinteractive/magic-carpet-2-hd#239] opened 2023-05-04 19:31 UTC
Hi, first, big thanks for your work to ressurrect MC2!

When trying to install, I always get the following error:
![image](https://user-images.githubusercontent.com/32574792/236309937-b696805e-9f1b-432e-be1b-bc3652646b56.png)

Ok brings me back to the interface of the installer.

If I create the "Extract" folder manually:
![image](https://user-images.githubusercontent.com/32574792/236310132-f621f655-49f2-4e90-a3a6-bed10f9572d3.png)

Next error message:
![image](https://user-images.githubusercontent.com/32574792/236310182-1c1f9ce0-44e3-42bd-84eb-6f9a3f17ba35.png)

Next Button in the installer does only get back to the error message.

**Comment by PhilippSPOTTERON** [comment] 2023-05-04 19:33
The installer creates a /GAME folder - if I delete that, the installer does something, opening up a DosBox,
But then the next error message appears:
![image](https://user-images.githubusercontent.com/32574792/236310639-9063d3b2-bd17-48d0-9dcc-a5716c34759a.png)

**Comment by PhilippSPOTTERON** [comment] 2023-05-05 12:14
Watched it further - before selecting the MC2 location, it is installing Magic Carpet 2 HD to a folder, creates files there.
Then the installer says "reverting back action" and deletes all the files in the /MagicCarpet2HD folder.
Should this be like that?

**Comment by PhilippSPOTTERON** [comment] 2023-05-05 12:18
Next try: using the x64 installer instead of the x32 one.
Different error message:
![image](https://user-images.githubusercontent.com/32574792/236455761-67a3670b-8269-4ad3-bb52-8333211ed075.png)

**Comment by thobbsinteractive** [comment] 2023-05-09 13:29
Hi Philipp,

Well this is just a big mess of stuff. Sorry for the late reply, I do not seem to be told in my own damn repo when I get issue reported!

The `Extract ` folder should be copied to the where ever you choose install the game (default for x64 is C:\Program Files\ReMC\Magic Capet 2 HD\). It then has the scripts required to get all the CD and Game data on the final page of the installer.

If there is an error installing it will rolled back. But the final page should not roll anything back as it happens **after** the files are copied but **before you get the original game data**. This is you can potentially manually fix in the install (that is why I put in the long list of instructions just in case!)

Obviously we cannot simply include the original game data in the install, EA might get a bit upset about that.

From your second screenshot it looks like it could not find the GOG install location? If you are using the original CD there is a option for that. I have not tested it myself though as my CD is 1000's of miles away. But It "should" work.

That last error looks permission based.

I am currently working on Joystick support but I will give this a look once that is done. One fix I can see is that it should just override any files copied to the Game folder, but I do not think that is the cause of all your issues.

I want to reproduce your error. Can you tell me: 
- Were you and Admin user on your PC?
- Where did you choose to install? It looks different from the default location?
- Where is your GOG game directory or are using the CD?

**Comment by Sarngeras** [comment] 2023-06-30 12:21
Hello!

Same problem with last installer.
It always rolls back.
Got the CD and GOG versions. That's not the problem.
Installers (32 ou 64) delete the CD_files they created before asking for them and NETHERW.

Tried the initial beta files (zip). Works. But if I use an installer afterwards to get last version, it deletes CD_files that already exist before asking for them.

**Comment by thobbsinteractive** [comment] 2023-06-30 12:26
Hi Sarngeras, I have hopefully fixed this, but was hoping to get the new sound stuff merged in before releasing. 
There is a permission issue with the installer, so it annoyingly rolls back. I have also implemented the ability to actually use the CD now.
It occurs to me that I might need to make a new release to fix this now since a few people are hitting it. It will try to do so over the weekend

**Comment by Sarngeras** [comment] 2023-06-30 12:35
Thanks for your answer and for your work!!!
It's a great idea to modernize this old treasure!
    Le vendredi 30 juin 2023 à 14:26:18 UTC+2, Tim Hobbs ***@***.***> a écrit :  
 
 


Hi Sarngeras, I have hopefully fixed this, but was hoping to get the new sound stuff merged in before releasing.
There is a permission issue with the installer, so it annoyingly rolls back. I have also implemented the ability to actually use the CD now.
It occurs to me that I might need to make a new release to fix this now since a few people are hitting it. It will try to do so over the weekend

**Comment by thobbsinteractive** [comment] 2023-07-03 18:57
This should be fixed now:
https://github.com/thobbsinteractive/magic-carpet-2-hd/releases/tag/0.9.3-alpha-stable
There are also instructions for manually installing it with the GOG Version

**Closed by thobbsinteractive** 2023-07-03 18:57 UTC

**Comment by PhilippSPOTTERON** [comment] 2023-07-03 22:12
Thank you very much! :) Looking forward to test it
